apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: simple-java
spec:
  customresourcedefinitions:
    owned:
    - kind: DemoResource
      name: demoresources.tools.opdev.io
      version: v1
  displayName: simple-java
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - tools.opdev.io
          resources:
          - demoresources
          - demoresources/status
          - demoresources/finalizers
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - create
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        serviceAccountName: simple-java-operator
      deployments:
      - name: simple-java-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/version: 0.0.1-SNAPSHOT
              app.kubernetes.io/name: simple-java-operator
          template:
            metadata:
              annotations:
                app.quarkus.io/commit-id: 3b3d5d0c20e27700bc33b2496656ad0c9e0bc4f7
                app.quarkus.io/build-timestamp: 2023-04-18 - 19:48:24 +0000
                prometheus.io/scrape: "true"
                prometheus.io/path: /q/metrics
                prometheus.io/port: "8080"
                prometheus.io/scheme: http
              labels:
                app.kubernetes.io/version: 0.0.1-SNAPSHOT
                app.kubernetes.io/name: simple-java-operator
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: itroyano/simple-java-operator:0.0.1-SNAPSHOT
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                name: simple-java-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
              serviceAccountName: simple-java-operator
    strategy: deployment
  installModes:
  - supported: true
    type: AllNamespaces
